### ISSUE TITLE
[FEATURE REQUEST] Cleanup after finishing start()

### ISSUE THREAD

**Issue by tylovejoy** [isigebengu-mikey/discord-ext-forms#13]
**Is your feature request related to a problem? Please describe.**
I love cleaning up things after commands have finished. From my understanding, there isn't a way to delete the embed from the form after finishing currently. 

**Describe the solution you'd like**
I would love an option to automatically delete the form after the start() command finishes.

**Describe alternatives you've considered**
Maybe an additional key in the returned dict holding the message_id of the embed.

**Comment by tylovejoy** [comment]
Also if a form is canceled, the "cancel" reply from a user still remains. I would like that to be deleted as well.

**Comment by isigebengu-mikey** [comment]
Would you prefer if I made it a handler, such as you would pass in your own function and it would run it on completion, or would you want it to be a pre-determined function?

**Comment by tylovejoy** [comment]
A pre-determined function would be best in my opinion.
