### ISSUE TITLE
[FEATURE REQUEST] Custom validation

### ISSUE THREAD

**Issue by tylovejoy** [isigebengu-mikey/discord-ext-forms#14]
**Is your feature request related to a problem? Please describe.**
Currently, there are a few validators that use d.py converters. I would like to be able to use my own specific boolean functions as a validator. 
Say I have a regex pattern that I want to enforce. The user has to complete the entire form before I can validate a specific entry to that form with the regex pattern. Then after the form is completed I can send the user an error, meaning the user has to go through the entire form again instead of using the nice retries option that validators use.

**Describe the solution you'd like**
To be able to use a custom bool function in place of current validations.

**Comment by tylovejoy** [comment]
This is what I did for the time being.


In `start()`, I added this:
```py    
if 'type' in self._questions[question].keys():
    question = self._questions[question]
    if 'type' in question.keys():
        while True:
            if callable(question['type']):
                if question['type'](and):
                    result = ans
                else:
                    result = False
            else:
                    result = await self.__validate_input(question['type'],and)
```

And then in `add_question`, I added a new parameter `v` and added this after the `if qtype:` block.
```py
if v:
    dictionary['type'] = v
    self._tries = 3
```

**Comment by isigebengu-mikey** [comment]
7e21570fcf47c313cb23aeb59a69459993ac997b and 464c21b4141d43d21f3e881cd2379970da5f846a add custom verification
