### ISSUE TITLE
No more limits?!

### ISSUE THREAD

**Issue by py-alpha-wolf** [isigebengu-mikey/discord-ext-forms#8]
I have just noticed that it is not possible to use CostumEmojis. However, I have directly the solution to it; in the file `reactions.py` is only the line 64 with the Assert to delete, after that it goes perfectly. In my experience, there are no new problems that occur, so I would like that in a future version, this bug is fixed :)
Greetings

**Comment by isigebengu-mikey** [comment]
in 864543feeb02012a776a879f3c099e3c8974b91a i've fixed it, i'll prob release a new version this upcoming weekend. thanks for the suggestion!
